name: Python package

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch base branch
      id: base_branch
      run: |
        git fetch --progress ${{ github.base_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        cat << 'EOF'
        ${{ toJSON(github) }}
        EOF
    - name: And finally, diff
      run: git diff --name-only origin/master
